In [ ]:
# 1. Import Libraries
import numpy as np
import pandas as pd

In [ ]:
#dataset
marks = np.array([
    [85, 80, 90],
    [70, 75, 65],
    [92, 88, 95],
    [60, 72, 68],
    [78, 82, 80]
])

marks

In [3]:
#Q1. Total marks obtained by each student
total_marks = np.sum(marks, axis=1)
total_marks

array([255, 210, 275, 200, 240])

In [4]:
#Q2. Average marks of each student
average_marks = np.mean(marks, axis=1)
average_marks

array([85.        , 70.        , 91.66666667, 66.66666667, 80.        ])

In [5]:
#Q3. Average marks in each subject
subject_average = np.mean(marks, axis=0)
subject_average

array([77. , 79.4, 79.6])

In [6]:
#Q4. Highest score in each subject
highest_subject_score = np.max(marks, axis=0)
highest_subject_score

array([92, 88, 95])

In [7]:
#Q5. Lowest score in each subject
lowest_subject_score = np.min(marks, axis=0)
lowest_subject_score

array([60, 72, 65])

In [8]:
#Q6. Students whose average marks are above 80
above_80 = average_marks > 80
above_80
average_marks[average_marks > 80]


array([85.        , 91.66666667])

In [9]:
#Q7. np.where() se Pass/Fail status
status = np.where(average_marks >= 40, "Pass", "Fail")
status


array(['Pass', 'Pass', 'Pass', 'Pass', 'Pass'], dtype='<U4')

In [10]:
#Q8. Highest-performing student ka index
highest_student_index = np.argmax(average_marks)
highest_student_index

np.int64(2)

In [11]:
#Q9. Standard deviation for each subject
subject_std = np.std(marks, axis=0)
subject_std

array([11.20714058,  5.57135531, 11.77454882])

In [12]:
#Q10. Final results ko Pandas DataFrame mein convert karna
df = pd.DataFrame({
    "Python": marks[:, 0],
    "SQL": marks[:, 1],
    "Machine Learning": marks[:, 2],
    "Total Marks": total_marks,
    "Average Marks": average_marks,
    "Status": status
})

df

,Python,SQL,Machine Learning,Total Marks,Average Marks,Status
0,85,80,90,255,85.000000,Pass
1,70,75,65,210,70.000000,Pass
2,92,88,95,275,91.666667,Pass
3,60,72,68,200,66.666667,Pass
4,78,82,80,240,80.000000,Pass
